spring:
  application:
    name: Solog-Backend

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}

grafana:
  url: ${GRAFANA_URL}
  token: ${GRAFANA_TOKEN}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}