# name: React CI/CD to EC2

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v4

#     - name: Login to Docker Hub
#       uses: docker/login-action@v3
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}

#     - name: Build and Push Docker Image
#       uses: docker/build-push-action@v5
#       with:
#         context: . 
#         push: true 
#         tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest
#         build-args: |
#           REACT_APP_PROD_BASE_URL=${{ secrets.REACT_APP_PROD_BASE_URL }}
#           REACT_APP_KIBANA_URL_AUTH=${{ secrets.REACT_APP_KIBANA_URL_AUTH }}
#           REACT_APP_KIBANA_URL_KMSG=${{ secrets.REACT_APP_KIBANA_URL_KMSG }}
#           REACT_APP_KIBANA_URL_SERVICE=${{ secrets.REACT_APP_KIBANA_URL_SERVICE }}
          

#     - name: Deploy to EC2
#       uses: appleboy/ssh-action@master 
#       with:
#         host: ${{ secrets.EC2_HOST }}             
#         username: ${{ secrets.EC2_USERNAME }}     
#         key: ${{ secrets.EC2_SSH_KEY }}         
#         script: |
#           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest
          
#           docker stop my-react-app-container || true
          
#           docker rm my-react-app-container || true
          
#           docker run -d -p 3000:3000 --name my-react-app-container ${{ secrets.DOCKERHUB_USERNAME }}/my-react-app:latest