name: Build and Push Frontend to ECR & Update Manifest

on:
  push:
    branches:
      - main
    paths:
      - 'FrontEnd/**'
  workflow_dispatch:
    inputs:
      target_cloud:
        description: '배포할 클라우드를 선택하세요'
        required: true
        default: 'azure'
        type: choice
        options:
          - azure
          - aws

env:
  TARGET : ${{ github.event_name == 'push' && 'azure' || github.event.inputs.target_cloud }}
  IMAGE_NAME: solog-frontend
  IMAGE_TAG: ${{ github.sha }}
  MANIFEST_REPO: lnaura/Solog-Webapp-CI-CD-Manifests
  MANIFEST_FILE_PATH: frontend/deployment.yaml
  WORKING_DIRECTORY: ./FrontEnd

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      # aws 단계
      - name: Configure AWS credentials
        if: ${{ env.TARGET == 'aws' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: ${{ env.TARGET == 'aws' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Azure 단계
      - name: Azure Login
        if: ${{ env.TARGET == 'azure' }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        if: ${{ env.TARGET == 'azure' }}
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          echo "REGISTRY_URL=$(az acr show --name ${{ secrets.ACR_NAME }} --query loginServer -o tsv)" >> $GITHUB_ENV
      
      # 공통
      - name: Build, tag, and push image
        run: |
          if [ "${{ env.TARGET }}" == "aws" ]; then
            REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          else
            REGISTRY="$REGISTRY_URL"
          fi

          FULL_IMAGE="$REGISTRY/${{ env.IMAGE_NAME }}"

          echo "Building Docker Image..."
          
          # Docker Build with Build Args
          docker build \
            --build-arg REACT_APP_PROD_BASE_URL=${{ secrets.REACT_APP_PROD_BASE_URL }} \
            --build-arg REACT_APP_KIBANA_URL_KMSG=${{ secrets.REACT_APP_KIBANA_URL_KMSG }} \
            --build-arg REACT_APP_KIBANA_URL_SERVICE=${{ secrets.REACT_APP_KIBANA_URL_SERVICE }} \
            --build-arg REACT_APP_KIBANA_URL_AUTH=${{ secrets.REACT_APP_KIBANA_URL_AUTH }} \
            -t $FULL_IMAGE:${{ env.IMAGE_TAG }} .
          
          echo "Pushing Docker Image..."
          docker push $FULL_IMAGE:${{ env.IMAGE_TAG }}
          docker tag $FULL_IMAGE:${{ env.IMAGE_TAG }} $FULL_IMAGE:latest
          docker push $FULL_IMAGE:latest

          echo "FINAL_REGISTRY=$REGISTRY" >> $GITHUB_ENV

      - name: Update Kubernetes Manifest
        run: |
          # 1. SSH 설정
          mkdir -p ~/.ssh
          echo "${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
          # 2. Git 설정
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 3. Manifest 리포지토리 클론
          cd /tmp
          git clone git@github.com:${{ env.MANIFEST_REPO }}.git
          
          cd /tmp/$(basename ${{ env.MANIFEST_REPO }})/overlays/${{ env.TARGET }}/frontend

          # Kustomize 명령어로 이미지 태그만 업데이트
          kustomize edit set image solog-frontend=${{ env.FINAL_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
          # 4. 변경 사항 푸시
          git add kustomization.yaml
          git commit -m "Update ${{ env.TARGET }} image tag to ${{ env.IMAGE_TAG }}"
          git push origin main